## import library


In [14]:
import os
from typing import Any

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from Preprocessing import style_df

# Set plotting backend options for pandas
pd.options.plotting.backend = "plotly"
from pandas.io.formats.style import Styler
from ydata_profiling import ProfileReport

# Load data


In [15]:
# # csv file
file_path = r"data\CRK_guild_boss.csv"


df_raw = pd.read_csv(file_path, parse_dates=True)

# pickled file
# file_path = r"data\CRK_guild_boss.pkl"
# df_raw = pd.read_pickle(file_path)


df_raw

Date  Season Round  GuildName GuildNameExtra  Trophies  \
0    2024-02-27       1   1-1  Spearmint      Spearmint  10513190   
1    2024-02-27       1   1-1      Vivid          Vivid  10510940   
2    2024-02-27       1   1-1    Nobless        Nobless  10251975   
3    2024-02-27       1   1-1      LAODA          LAODA  10011795   
4    2024-02-27       1   1-1        미라클  미라클 (miracle)   9930645   
..          ...     ...   ...        ...            ...       ...   
281  2024-05-28       4   4-3       MyTH           MyTH  10346185   
282  2024-05-28       4   4-3   Nobility       Nobility  10445040   
283  2024-05-28       4   4-3       S7AR           S7AR  10270005   
284  2024-05-28       4   4-3         감동  감동 (gam-dong)   9872795   
285  2024-05-28       4   4-3     DEKWAT         DEKWAT  10286850   

     SeasonTotal  RoundRank  DiffRoundRank  SeasonRank  DiffSeasonRank  \
0       10513190          1              0           1               0   
1       10510940          2              0           2               0   
2       10251975          3              0           3               0   
3       10011795          4              0           4               0   
4        9930645          5              0           5               0   
..           ...        ...            ...         ...             ...   
281     30139130         17             -1          16               0   
282     30041855         16              2          17               1   
283     29984580         19             -2          18              -1   
284     29384460         20             -1          19               0   
285     29698740         18              2          20               0   

     Improvement  GrowthRate  
0              0    0.000000  
1              0    0.000000  
2              0    0.000000  
3              0    0.000000  
4              0    0.000000  
..           ...         ...  
281       401815    4.040628  
282       570010    5.772236  
283       327380    3.292692  
284        79735    0.814199  
285       585060    6.030434  

[286 rows x 13 columns]

In [16]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 286 entries, 0 to 285
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Date            286 non-null    object 
 1   Season          286 non-null    int64  
 2   Round           286 non-null    object 
 3   GuildName       286 non-null    object 
 4   GuildNameExtra  286 non-null    object 
 5   Trophies        286 non-null    int64  
 6   SeasonTotal     286 non-null    int64  
 7   RoundRank       286 non-null    int64  
 8   DiffRoundRank   286 non-null    int64  
 9   SeasonRank      286 non-null    int64  
 10  DiffSeasonRank  286 non-null    int64  
 11  Improvement     286 non-null    int64  
 12  GrowthRate      286 non-null    float64
dtypes: float64(1), int64(8), object(4)
memory usage: 29.2+ KB


In [17]:
df_raw.columns.to_list()

['Date',
 'Season',
 'Round',
 'GuildName',
 'GuildNameExtra',
 'Trophies',
 'SeasonTotal',
 'RoundRank',
 'DiffRoundRank',
 'SeasonRank',
 'DiffSeasonRank',
 'Improvement',
 'GrowthRate']

# Clean data


In [18]:
def clean_data(df: pd.DataFrame) -> pd.DataFrame:

    # Change column type to category for column: 'Season','Round','Rank'

    df = df.astype(
        {
            "Season": "category",
            "RoundRank": "category",
            "SeasonRank": "category",
            "Round": "category",
        }
    )

    df.Season = df.Season.cat.as_ordered()
    df.Round = df.Round.cat.as_ordered()
    df.RoundRank = df.RoundRank.cat.as_ordered()
    df.SeasonRank = df.SeasonRank.cat.as_ordered()

    # Change column type to string for column: 'GuildName'

    df = df.astype({"GuildName": "string", "GuildNameExtra": "string"})

    # Change column type to datetime for column: 'Date'

    df.Date = pd.to_datetime(df.Date)
    return df


data = clean_data(df_raw.copy())
data

Date Season Round  GuildName GuildNameExtra  Trophies  SeasonTotal  \
0   2024-02-27      1   1-1  Spearmint      Spearmint  10513190     10513190   
1   2024-02-27      1   1-1      Vivid          Vivid  10510940     10510940   
2   2024-02-27      1   1-1    Nobless        Nobless  10251975     10251975   
3   2024-02-27      1   1-1      LAODA          LAODA  10011795     10011795   
4   2024-02-27      1   1-1        미라클  미라클 (miracle)   9930645      9930645   
..         ...    ...   ...        ...            ...       ...          ...   
281 2024-05-28      4   4-3       MyTH           MyTH  10346185     30139130   
282 2024-05-28      4   4-3   Nobility       Nobility  10445040     30041855   
283 2024-05-28      4   4-3       S7AR           S7AR  10270005     29984580   
284 2024-05-28      4   4-3         감동  감동 (gam-dong)   9872795     29384460   
285 2024-05-28      4   4-3     DEKWAT         DEKWAT  10286850     29698740   

    RoundRank  DiffRoundRank SeasonRank  DiffSeasonRank  Improvement  \
0           1              0          1               0            0   
1           2              0          2               0            0   
2           3              0          3               0            0   
3           4              0          4               0            0   
4           5              0          5               0            0   
..        ...            ...        ...             ...          ...   
281        17             -1         16               0       401815   
282        16              2         17               1       570010   
283        19             -2         18              -1       327380   
284        20             -1         19               0        79735   
285        18              2         20               0       585060   

     GrowthRate  
0      0.000000  
1      0.000000  
2      0.000000  
3      0.000000  
4      0.000000  
..          ...  
281    4.040628  
282    5.772236  
283    3.292692  
284    0.814199  
285    6.030434  

[286 rows x 13 columns]

In [19]:
style_df(data)

In [20]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 286 entries, 0 to 285
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype         
---  ------          --------------  -----         
 0   Date            286 non-null    datetime64[ns]
 1   Season          286 non-null    category      
 2   Round           286 non-null    category      
 3   GuildName       286 non-null    string        
 4   GuildNameExtra  286 non-null    string        
 5   Trophies        286 non-null    int64         
 6   SeasonTotal     286 non-null    int64         
 7   RoundRank       286 non-null    category      
 8   DiffRoundRank   286 non-null    int64         
 9   SeasonRank      286 non-null    category      
 10  DiffSeasonRank  286 non-null    int64         
 11  Improvement     286 non-null    int64         
 12  GrowthRate      286 non-null    float64       
dtypes: category(4), datetime64[ns](1), float64(1), int64(5), string(2)
memory usage: 23.6 KB


In [21]:
for col in data.select_dtypes(include=["category"]):
    print("data : ", col, "\n", data[col].cat.categories, "\n", "\n")

data :  Season 
 Index([1, 2, 3, 4], dtype='int64') 
 

data :  Round 
 Index(['1-1', '1-2', '1-3', '1-4', '2-1', '2-2', '2-3', '2-4', '3-1', '3-2',
       '3-3', '4-1', '4-2', '4-3'],
      dtype='object') 
 

data :  RoundRank 
 Index([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21],
      dtype='int64') 
 

data :  SeasonRank 
 Index([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24],
      dtype='int64') 
 



# EDA


In [22]:
report = ProfileReport(
    df=data,
    title=f"Exploratory Data Analysis report: {file_path}",
    dark_mode=True,
    config_file=r"report\config.json",
)

## displaying the report as a set of widgets


In [23]:
# report.to_widgets()

In [ ]:
report.to_notebook_iframe()

## generate a HTML report file


In [ ]:
save_path = r"report/CRK_guild_boss_EDA_report.html"
# save_path

report.to_file(save_path)

# Report table


In [25]:
rename_idx = {
    "미라클": "미라클 (miracle)",
    "님": "님 (nim)",
    "오로라": "오로라 (aurora)",
    "무야호": "무야호 (muyaho)",
    "열매": "열매 (yeol-mae)",
    "이지스": "이지스 (aegis)",
    "재난경보": "재난경보 (jae-nan-gyeong-bo)",
    "사혼": "사혼 (sa-hon)",
    "쿠벤저스": "쿠벤저스 (cubengers)",
    "秋": "秋 (aki)",
}

In [ ]:
rep_table = (
    data.pivot_table(
        index="GuildNameExtra",
        columns=["Round"],
        values=["SeasonRank", "Trophies"],
        aggfunc="max",
        observed=True,
    )
    .sort_index(axis=1, ascending=False)
    .sort_values(by=("SeasonRank", "3-2"))
)

rep_table.rename(index=rename_idx, inplace=True)

rep_table = rep_table.astype("Int64")

style_df(rep_table.T)

# Plots


## Ranking Over Time of Top 10

In [30]:
top10_recent = data[
    (data.SeasonRank <= 10) & (data.Round == data.Round.max())
].GuildName.unique()
max_date = str(data[data.GuildName.isin(top10_recent)].Date.max()).split(" ")[0]

fig = px.line(
    data[data.GuildName.isin(top10_recent)],
    x="Round",
    y="SeasonRank",
    color="GuildNameExtra",
    color_discrete_sequence=px.colors.qualitative.G10,
    text="SeasonRank",
    markers=True,
    line_shape="linear",
    labels={"GuildNameExtra": "Guild", "Round": "Season"},
    template="plotly_white",
    hover_name="GuildNameExtra",
    hover_data={
        "GuildNameExtra": False,
        "Round": True,
        "SeasonRank": False,
        "Date": "|%d %B %Y",
        "Trophies": ":,.0f",
        "SeasonTotal": ":,.0f",
    },
    height=900,
    width=1600,
)


fig.update_yaxes(
    title="SeasonRank", ticklabelstep=1, range=[14, 0], showgrid=False, visible=False
)

fig.update_xaxes(title="Season", showgrid=False)

fig.update_traces(
    marker_symbol="circle",
    marker_size=20,
    textposition="middle center",
    textfont=dict(family="Arial", size=12, color="White"),
)


annotations = []


annotations.append(
    dict(
        text=f"Created by: SantaMonica @ MolochTH<br>Last update: {max_date}",
        xref="paper",
        yref="paper",
        x=1.16,
        y=-0.05,
        xanchor="right",
        yanchor="top",
        font=dict(family="Arial", size=12, color="rgb(150,150,150)"),
        showarrow=False,
    )
)

fig.update_layout(
    annotations=annotations,
    title_text=f"The Cookie Run Kingdom: Top 10 guilds in Dark Cacao Server <br>(Guild Ranking Over Time)",
    title_font_family="Arial",
    title_font_size=30,
    legend=dict(
        # x=0,
        # y=1,
        # traceorder="reversed",
        font=dict(family="Arial", size=20, color="black"),
        bgcolor=None,
        bordercolor=None,
        borderwidth=0,
    ),
    hovermode="closest",
)

fig.show()

In [31]:
report_path = r"report\top10_ranking_overtime.html"
fig.write_html(report_path)

## Ranking Over Time of Top 20

In [33]:
top10_recent = data[
    (data.SeasonRank <= 10) & (data.Round == data.Round.max())
].GuildName.unique()

max_date = str(data[data.GuildName.isin(top10_recent)].Date.max()).split(" ")[0]

fig = px.line(
    data[(data.SeasonRank <= 20)],
    x="Round",
    y="SeasonRank",
    color="GuildNameExtra",
    color_discrete_sequence=px.colors.qualitative.G10,
    text="SeasonRank",
    markers=True,
    line_shape="linear",
    labels={"GuildNameExtra": "Guild", "Round": "Season"},
    template="plotly_white",
    hover_name="GuildNameExtra",
    hover_data={
        "GuildNameExtra": False,
        "Round": True,
        "SeasonRank": False,
        "Date": "|%d %B %Y",
        "Trophies": ":,.0f",
        "SeasonTotal": ":,.0f",
    },
    height=1100,
    width=1600,
)


fig.update_yaxes(
    title="SeasonRank", ticklabelstep=1, range=[21, 0], showgrid=False, visible=False
)

fig.update_xaxes(title="Season", showgrid=False)

fig.update_traces(
    marker_symbol="circle",
    marker_size=20,
    textposition="middle center",
    textfont=dict(family="Arial", size=11, color="White"),
)


annotations = []


annotations.append(
    dict(
        text=f"Created by: SantaMonica @ MolochTH<br>Last update: {max_date}",
        xref="paper",
        yref="paper",
        x=1.2,
        y=-0.05,
        xanchor="right",
        yanchor="top",
        font=dict(
            family="Arial",
            size=10,
            color="rgb(150,150,150)",
        ),
        showarrow=False,
    )
)

fig.update_layout(
    annotations=annotations,
    title_text=f"The Cookie Run Kingdom: Top 20 guilds in Dark Cacao Server <br>(Guild Ranking Over Time)",
    title_font_family="Arial",
    title_font_size=30,
    legend=dict(
        # x=0,
        # y=1,
        # traceorder="reversed",
        font=dict(
            family="Arial",
            size=15,
            color="black",
        ),
        bgcolor=None,
        bordercolor=None,
        borderwidth=None,
    ),
    hovermode="closest",
)

fig.show()

In [34]:
report_path = r"report\top20_ranking_overtime.html"
fig.write_html(report_path)

---


In [ ]:
(np.arange(2001, 2014),) * 4

(array([2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
        2012, 2013]),
 array([2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
        2012, 2013]),
 array([2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
        2012, 2013]),
 array([2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
        2012, 2013]))

In [ ]:
plot_data = rep_table.T

plot_data.loc[["Trophies"], :].values


plot_data.columns.values

x_data = np.vstack(
    tup=(np.array(plot_data.index.get_level_values(level=1).values),) * 20
)

len(x_data)

20

In [ ]:
plot_data.loc[["Rank"], :].values

array([[2, 1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 17, 18, 20,
        16, <NA>, <NA>, 19, <NA>],
       [2, 1, 3, 6, 4, 5, 7, 8, 9, 10, 11, 12, 13, 14, 15, 18, 17, 20,
        16, <NA>, <NA>, 19, <NA>],
       [2, 1, 3, 5, 4, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 18, 17, 20,
        16, <NA>, <NA>, 19, <NA>],
       [2, 1, 3, 4, 5, 6, 8, 7, 9, 10, 11, 12, 14, 13, 15, 16, 17, 18,
        19, 21, 20, <NA>, <NA>],
       [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, <NA>, <NA>, <NA>],
       [1, 2, 3, 4, 5, 6, 7, 9, 8, 10, 11, 12, 13, 14, 16, 15, 17, 18,
        19, 20, <NA>, <NA>, <NA>],
       [1, 2, 3, 6, 4, 7, 5, 8, 9, 10, 11, 12, 14, 13, 18, 19, 16, 17,
        15, 20, <NA>, <NA>, <NA>],
       [1, 2, 3, 6, 4, 7, 5, 8, 9, 10, 11, 12, 14, 13, 19, 18, 16, 17,
        15, 20, <NA>, <NA>, <NA>],
       [1, 2, 3, 5, 6, 8, 4, 7, 9, 10, 11, 12, 15, 13, 18, 19, 16, 17,
        14, 20, <NA>, <NA>, <NA>],
       [1, 2, 3, 5, 6, 8, 4, 7, 11, 10, 12, 13, 

# PyGWalker

In [ ]:
import pygwalker as pyg

walker = pyg.walk(data)

Box(children=(HTML(value='<div id="ifr-pyg-000619a064c9462bHT3LnRuabmGKMEyj" style="height: auto">\n    <head>…

## Guild Boss Trophies Over Time

In [ ]:
fig = px.line(
    data[data.GuildName.isin(top10_recent)],
    x="Round",
    y="Trophies",
    color="GuildName",
    color_discrete_sequence=px.colors.qualitative.G10_r,
    markers=True,
    hover_data={
        "GuildName": False,
        "Rank": ":,.0f",
        "Date": "|%B %d, %Y",
        "Trophies": ":,.0f",
    },
    hover_name="GuildName",
    title="Guild Boss Trophies Over Time",
    labels={"Rank": "Rank", "Round": "Season", "Trophies": "Trophies"},
    template="simple_white",
    height=800,
)


fig.update_yaxes(showgrid=True)


fig.show()

In [ ]:
report_path = r"report\top10_trophies_overtime.html"
fig.write_html(report_path)

## Example

In [ ]:
title = "Main Source for News"
labels = ["Television", "Newspaper", "Internet", "Radio"]
colors = ["rgb(67,67,67)", "rgb(115,115,115)", "rgb(49,130,189)", "rgb(189,189,189)"]

mode_size = [8, 8, 12, 8]
line_size = [2, 2, 4, 2]

x_data = np.vstack((np.arange(2001, 2014),) * 4)

y_data = np.array(
    [
        [74, 82, 80, 74, 73, 72, 74, 70, 70, 66, 66, 69],
        [45, 42, 50, 46, 36, 36, 34, 35, 32, 31, 31, 28],
        [13, 14, 20, 24, 20, 24, 24, 40, 35, 41, 43, 50],
        [18, 21, 18, 21, 16, 14, 13, 18, 17, 16, 19, 23],
    ]
)
print(list(zip(y_data, labels, colors)))

x_data

[(array([74, 82, 80, 74, 73, 72, 74, 70, 70, 66, 66, 69]), 'Television', 'rgb(67,67,67)'), (array([45, 42, 50, 46, 36, 36, 34, 35, 32, 31, 31, 28]), 'Newspaper', 'rgb(115,115,115)'), (array([13, 14, 20, 24, 20, 24, 24, 40, 35, 41, 43, 50]), 'Internet', 'rgb(49,130,189)'), (array([18, 21, 18, 21, 16, 14, 13, 18, 17, 16, 19, 23]), 'Radio', 'rgb(189,189,189)')]


array([[2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
        2012, 2013],
       [2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
        2012, 2013],
       [2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
        2012, 2013],
       [2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
        2012, 2013]])

# Example

In [ ]:
fig = go.Figure()

for i in range(0, 4):
    fig.add_trace(
        go.Scatter(
            x=x_data[i],
            y=y_data[i],
            mode="lines",
            name=labels[i],
            line=dict(color=colors[i], width=line_size[i]),
            connectgaps=True,
        )
    )

    # endpoints
    fig.add_trace(
        go.Scatter(
            x=[x_data[i][0], x_data[i][-1]],
            y=[y_data[i][0], y_data[i][-1]],
            mode="markers",
            marker=dict(color=colors[i], size=mode_size[i]),
        )
    )

fig.update_layout(
    xaxis=dict(
        showline=True,
        showgrid=False,
        showticklabels=True,
        linecolor="rgb(204, 204, 204)",
        linewidth=2,
        ticks="outside",
        tickfont=dict(
            family="Arial",
            size=12,
            color="rgb(82, 82, 82)",
        ),
    ),
    yaxis=dict(
        showgrid=False,
        zeroline=False,
        showline=False,
        showticklabels=False,
    ),
    autosize=False,
    margin=dict(
        autoexpand=False,
        l=100,
        r=20,
        t=110,
    ),
    showlegend=False,
    plot_bgcolor="white",
)

annotations = []

# Adding labels
for y_trace, label, color in zip(y_data, labels, colors):
    # labeling the left_side of the plot
    annotations.append(
        dict(
            xref="paper",
            x=0.05,
            y=y_trace[0],
            xanchor="right",
            yanchor="middle",
            text=label + " {}%".format(y_trace[0]),
            font=dict(family="Arial", size=16),
            showarrow=False,
        )
    )
    # labeling the right_side of the plot
    annotations.append(
        dict(
            xref="paper",
            x=0.95,
            y=y_trace[11],
            xanchor="left",
            yanchor="middle",
            text="{}%".format(y_trace[11]),
            font=dict(family="Arial", size=16),
            showarrow=False,
        )
    )
# Title
annotations.append(
    dict(
        xref="paper",
        yref="paper",
        x=0.0,
        y=1.05,
        xanchor="left",
        yanchor="bottom",
        text="Main Source for News",
        font=dict(family="Arial", size=30, color="rgb(37,37,37)"),
        showarrow=False,
    )
)
# Source
annotations.append(
    dict(
        xref="paper",
        yref="paper",
        x=0.5,
        y=-0.1,
        xanchor="center",
        yanchor="top",
        text="Source: PewResearch Center & " + "Storytelling with data",
        font=dict(family="Arial", size=12, color="rgb(150,150,150)"),
        showarrow=False,
    )
)

fig.update_layout(annotations=annotations)

fig.show()

## waterfall

In [ ]:
import plotly.graph_objects as go

# Assuming data2 is the DataFrame with the added "Trophies" column

fig = go.Figure()

for guild, dat in data.groupby("GuildNameExtra"):
    improvement = dat["Improvement"]
    fig.add_trace(
        go.Waterfall(
            orientation="v",
            x=dat["Round"],
            y=improvement,
            name=guild,
            # text=f"{guild} ({growth_rates_percentage.round(2).astype(str)}%)",
            # markers=dict(),
            decreasing=dict(marker=dict(color="red")),
            increasing=dict(marker=dict(color="green")),
        )
    )

fig.update_layout(
    title="Waterfall Chart for Round Over Round Growth Over Time",
    xaxis_title="Round",
    yaxis_title="Improvement",
    # autosize=False,
    # width=800,
    height=800,
)

fig.show()

NameError: name 'data' is not defined

In [ ]:
data

Date Season Round Rank  GuildName GuildNameExtra  Trophies  \
0   2024-02-27      1   1-1    1  Spearmint      Spearmint  10513190   
1   2024-02-27      1   1-1    2      Vivid          Vivid  10510940   
2   2024-02-27      1   1-1    3    Nobless        Nobless  10251975   
3   2024-02-27      1   1-1    4      LAODA          LAODA  10011795   
4   2024-02-27      1   1-1    5        미라클  미라클 (miracle)   9930645   
..         ...    ...   ...  ...        ...            ...       ...   
281 2024-05-28      4   4-3   16       MyTH           MyTH  10346185   
282 2024-05-28      4   4-3   17   Nobility       Nobility  10445040   
283 2024-05-28      4   4-3   18       S7AR           S7AR  10270005   
284 2024-05-28      4   4-3   19         감동  감동 (gam-dong)   9872795   
285 2024-05-28      4   4-3   20     DEKWAT         DEKWAT  10286850   

     SeasonTotal  Improvement  GrowthRate  
0       10513190            0    0.000000  
1       10510940            0    0.000000  
2       10251975            0    0.000000  
3       10011795            0    0.000000  
4        9930645            0    0.000000  
..           ...          ...         ...  
281     30139130       401815    4.040628  
282     30041855       570010    5.772236  
283     29984580       327380    3.292692  
284     29384460        79735    0.814199  
285     29698740       585060    6.030434  

[286 rows x 10 columns]

In [ ]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Assuming data2 is the DataFrame with the added "GrowthRate" column

fig = go.Figure()


for guild, dat in data.groupby("GuildName"):
    growth_rates_percentage = dat["GrowthRate"]
    fig.add_trace(
        go.Waterfall(
            orientation="v",
            x=dat["Round"],
            y=growth_rates_percentage,
            name=guild,
            # text=f"{guild}",
            decreasing=dict(marker=dict(color="red")),
            increasing=dict(marker=dict(color="green")),
        )
    )

fig.update_layout(
    title="Waterfall Chart for Growth Rate over Time",
    xaxis_title="Round",
    yaxis_title="Growth Rate (%)",
    autosize=False,
    width=800,
    height=600,
    # yaxis=dict(type="log"),  # Set the y-axis type to logarithmic
)

fig.show()

In [ ]:
top10_recent = data[
    (data.Rank <= 10) & (data.Round == data.Round.max())
].GuildName.unique()

data[data.GuildName.isin(top10_recent)]


def view_table(df):

    return df.style.format(
        precision=2,
        thousands=",",
        decimal=".",
    )


# view_table(data[data.GuildName.isin(top10_recent)])

In [ ]:
data_top10 = data[data.GuildName.isin(top10_recent)]
fig = make_subplots(rows=5, cols=2, subplot_titles=data_top10.GuildNameExtra.unique())

for i, guild in enumerate(data_top10):
    dataset = data_top10
    growth_rates_percentage = dataset["GrowthRate"]
    fig.add_trace(
        go.Waterfall(
            orientation="v",
            x=dataset["Round"],
            y=growth_rates_percentage,
            name=guild,
            text=f"{guild}",  # ({growth_rates_percentage.astype(str)}%)",
            decreasing=dict(marker=dict(color="red")),
            increasing=dict(marker=dict(color="green")),
        ),
        col=(i // 5) + 1,  # Calculate the row number
        row=(i % 5) + 1,  # Calculate the column number
    )

fig.update_layout(
    title="Waterfall Chart for Top 10 Guilds (Formatted as Percentage)",
    xaxis_title="Round",
    yaxis_title="Growth Rate (%)",
    autosize=True,
    grid=dict(rows=5, columns=2, pattern="independent"),
)

fig.show()