## import library


In [1]:
import os
from typing import Any

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from pandas.io.formats.style import Styler
from ydata_profiling import ProfileReport

# Load data


In [2]:
# # csv file
file_path = r"data\CRK_guild_boss.csv"


df_raw = pd.read_csv(file_path, parse_dates=True)

# pickled file
# file_path = r"data\CRK_guild_boss.pkl"
# df_raw = pd.read_pickle(file_path)


df_raw

Date  Season Round  Rank  GuildName GuildNameExtra  Trophies  \
0    2024-02-27       1   1-1     1  Spearmint      Spearmint  10513190   
1    2024-02-27       1   1-1     2      Vivid          Vivid  10510940   
2    2024-02-27       1   1-1     3    Nobless        Nobless  10251975   
3    2024-02-27       1   1-1     4      LAODA          LAODA  10011795   
4    2024-02-27       1   1-1     5        미라클  미라클 (miracle)   9930645   
..          ...     ...   ...   ...        ...            ...       ...   
281  2024-05-28       4   4-3    16       MyTH           MyTH  10346185   
282  2024-05-28       4   4-3    17   Nobility       Nobility  10445040   
283  2024-05-28       4   4-3    18       S7AR           S7AR  10270005   
284  2024-05-28       4   4-3    19         감동  감동 (gam-dong)   9872795   
285  2024-05-28       4   4-3    20     DEKWAT         DEKWAT  10286850   

     SeasonTotal  Improvement  GrowthRate  
0       10513190            0    0.000000  
1       10510940            0    0.000000  
2       10251975            0    0.000000  
3       10011795            0    0.000000  
4        9930645            0    0.000000  
..           ...          ...         ...  
281     30139130       401815    4.040628  
282     30041855       570010    5.772236  
283     29984580       327380    3.292692  
284     29384460        79735    0.814199  
285     29698740       585060    6.030434  

[286 rows x 10 columns]

In [8]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 286 entries, 0 to 285
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Date            286 non-null    object 
 1   Season          286 non-null    int64  
 2   Round           286 non-null    object 
 3   Rank            286 non-null    int64  
 4   GuildName       286 non-null    object 
 5   GuildNameExtra  286 non-null    object 
 6   Trophies        286 non-null    int64  
 7   SeasonTotal     286 non-null    int64  
 8   Improvement     286 non-null    int64  
 9   GrowthRate      286 non-null    float64
dtypes: float64(1), int64(5), object(4)
memory usage: 22.5+ KB


# Clean data


In [10]:
def df_style(df: pd.DataFrame) -> Styler:
    """
    format the table when displaying it in the notebook
    """
    return (
        df.style.highlight_null(props="background-color: rgba(238, 238, 238, 0.5)")
        .highlight_between(
            left=None,
            right=-0.001,
            props="font-weight:bold;color:red",
            subset=["Improvement", "GrowthRate"],
        )
        .format(precision=2, thousands=",", decimal=".", na_rep="-")
    )


def clean_data(df: pd.DataFrame) -> pd.DataFrame:

    # Change column type to category for column: 'Season','Round','Rank'

    df = df.astype({"Season": "category", "Rank": "category", "Round": "category"})

    df.Season = df.Season.cat.as_ordered()

    df.Round = df.Round.cat.as_ordered()

    df.Rank = df.Rank.cat.as_ordered()

    # Change column type to string for column: 'GuildName'

    df = df.astype({"GuildName": "string", "GuildNameExtra": "string"})

    # Change column type to datetime for column: 'Date'

    df.Date = pd.to_datetime(df.Date)
    return df


data = clean_data(df_raw.copy())
data

Date Season Round Rank  GuildName GuildNameExtra  Trophies  \
0   2024-02-27      1   1-1    1  Spearmint      Spearmint  10513190   
1   2024-02-27      1   1-1    2      Vivid          Vivid  10510940   
2   2024-02-27      1   1-1    3    Nobless        Nobless  10251975   
3   2024-02-27      1   1-1    4      LAODA          LAODA  10011795   
4   2024-02-27      1   1-1    5        미라클  미라클 (miracle)   9930645   
..         ...    ...   ...  ...        ...            ...       ...   
281 2024-05-28      4   4-3   16       MyTH           MyTH  10346185   
282 2024-05-28      4   4-3   17   Nobility       Nobility  10445040   
283 2024-05-28      4   4-3   18       S7AR           S7AR  10270005   
284 2024-05-28      4   4-3   19         감동  감동 (gam-dong)   9872795   
285 2024-05-28      4   4-3   20     DEKWAT         DEKWAT  10286850   

     SeasonTotal  Improvement  GrowthRate  
0       10513190            0    0.000000  
1       10510940            0    0.000000  
2       10251975            0    0.000000  
3       10011795            0    0.000000  
4        9930645            0    0.000000  
..           ...          ...         ...  
281     30139130       401815    4.040628  
282     30041855       570010    5.772236  
283     29984580       327380    3.292692  
284     29384460        79735    0.814199  
285     29698740       585060    6.030434  

[286 rows x 10 columns]

In [5]:
df_style(data)

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 286 entries, 0 to 285
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype         
---  ------          --------------  -----         
 0   Date            286 non-null    datetime64[ns]
 1   Season          286 non-null    category      
 2   Round           286 non-null    category      
 3   Rank            286 non-null    category      
 4   GuildName       286 non-null    string        
 5   GuildNameExtra  286 non-null    string        
 6   Trophies        286 non-null    int64         
 7   SeasonTotal     286 non-null    int64         
 8   Improvement     286 non-null    int64         
 9   GrowthRate      286 non-null    float64       
dtypes: category(3), datetime64[ns](1), float64(1), int64(3), string(2)
memory usage: 18.2 KB


In [7]:
for col in ["Season", "Round", "Rank"]:
    print("data : ", col, "\n", data[col].cat.categories, "\n", "\n")

data :  Season 
 Index([1, 2, 3, 4], dtype='int64') 
 

data :  Round 
 Index(['1-1', '1-2', '1-3', '1-4', '2-1', '2-2', '2-3', '2-4', '3-1', '3-2',
       '3-3', '4-1', '4-2', '4-3'],
      dtype='object') 
 

data :  Rank 
 Index([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24],
      dtype='int64') 
 



# EDA


In [12]:
report = ProfileReport(
    df=data,
    title=f"Exploratory Data Analysis report: {file_path}",
    dark_mode=True,
    config_file=r"report\config.json",
)

## displaying the report as a set of widgets


In [9]:
# report.to_widgets()

In [13]:
report.to_notebook_iframe()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

## generate a HTML report file


In [14]:
save_path = r"report/CRK_guild_boss_EDA_report.html"
# save_path

report.to_file(save_path)

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

# Report table


In [15]:
rename_idx = {
    "미라클": "미라클 (miracle)",
    "님": "님 (nim)",
    "오로라": "오로라 (aurora)",
    "무야호": "무야호 (muyaho)",
    "열매": "열매 (yeol-mae)",
    "이지스": "이지스 (aegis)",
    "재난경보": "재난경보 (jae-nan-gyeong-bo)",
    "사혼": "사혼 (sa-hon)",
    "쿠벤저스": "쿠벤저스 (cubengers)",
    "秋": "秋 (aki)",
}

In [16]:
rep_table = (
    data.pivot_table(
        index="GuildName",
        columns=["Round"],
        values=["Rank", "Trophies"],
        aggfunc="max",
        observed=True,
    )
    .sort_index(axis=1, ascending=False)
    .sort_values(by=("Rank", "3-2"))
)

rep_table.rename(index=rename_idx, inplace=True)

rep_table = rep_table.astype("Int64")

rep_table.T

GuildName       Spearmint     Vivid   Nobless   님 (nim)     LAODA  \
         Round                                                      
Trophies 4-3     12495730  12498900  11943105  12114505  11859400   
         4-2     11768065  11782185  11407690  11230760  11411315   
         4-1     11773265  11856320  11397880  11240180  11242265   
         3-3     11122140  11398630  10865505  10791950  10778080   
         3-2     11211090  11115440  10781320  10683770  10691550   
         3-1     11216060  11041545  10792615  10621980  10609375   
         2-4     11044970  11128220  10767570  10426780  10600065   
         2-3     11037250  11028425  10762930  10351645  10520225   
         2-2     11036070  10945065  10532845  10350005  10340180   
         2-1     10949190  10866400  10517570  10262110  10260975   
         1-4     10779410  10702360  10349095  10005140  10174935   
         1-3     10770870  10690270  10424260   9678260  10103600   
         1-2     10692545  10598695  10259645  10173275  10091870   
         1-1     10513190  10510940  10251975   9688065  10011795   
Rank     4-3            2         1         3         4         5   
         4-2            2         1         3         6         4   
         4-1            2         1         3         5         4   
         3-3            2         1         3         4         5   
         3-2            1         2         3         4         5   
         3-1            1         2         3         4         5   
         2-4            1         2         3         6         4   
         2-3            1         2         3         6         4   
         2-2            1         2         3         5         6   
         2-1            1         2         3         5         6   
         1-4            1         2         3         6         4   
         1-3            1         2         3         6         4   
         1-2            1         2         3         6         4   
         1-1            1         2         3         6         4   

GuildName       이지스 (aegis)  미라클 (miracle)     Crown  MolochTH  열매 (yeol-mae)  \
         Round                                                                  
Trophies 4-3       11851050       11762665  11572160  11477380       11665790   
         4-2       11408945       11233590  11226560  11142940       10885185   
         4-1       11148110       11141720  11053810  11048890       11045180   
         3-3       10784790       10518955  10679720  10598615       10433560   
         3-2       10614170       10599700  10595575  10520085       10350345   
         3-1       10525165       10510435  10430030  10430590       10265120   
         2-4       10433950       10433690  10508315  10256305       10188930   
         2-3       10361535       10346675  10084940  10262850       10108120   
         2-2       10186940       10352155  10165775  10094570        9934520   
         2-1       10018860       10343795  10165695   9931170        9936820   
         1-4        9936100       10263565  10085080   9841245        9686065   
         1-3        9614385       10096910   9835780   9763490        9685015   
         1-2        9367650        9930695   9836010   9530190        9683165   
         1-1        9286600        9930645   9591650   9356625        9516665   
Rank     4-3              6              7         8         9             10   
         4-2              5              7         8         9             10   
         4-1              6              7         8         9             10   
         3-3              6              8         7         9             10   
         3-2              6              7         8         9             10   
         3-1              6              7         9         8             10   
         2-4              7              5         8         9             10   
         2-3              7              5         8         9    

# Plots


## Ranking Over Time of Top 10

In [17]:
top10_recent = data[
    (data.Rank <= 10) & (data.Round == data.Round.max())
].GuildName.unique()
max_date = str(data[data.GuildName.isin(top10_recent)].Date.max()).split(" ")[0]

fig = px.line(
    data[data.GuildName.isin(top10_recent)],
    x="Round",
    y="Rank",
    color="GuildNameExtra",
    color_discrete_sequence=px.colors.qualitative.G10,
    text="Rank",
    markers=True,
    line_shape="linear",
    labels={"GuildNameExtra": "Guild", "Round": "Season"},
    template="plotly_white",
    hover_name="GuildNameExtra",
    hover_data={
        "GuildNameExtra": False,
        "Round": True,
        "Rank": False,
        "Date": "|%d %B %Y",
        "Trophies": ":,.0f",
        "SeasonTotal": ":,.0f",
    },
    height=900,
    width=1600,
)


fig.update_yaxes(
    title="Rank", ticklabelstep=1, range=[14, 0], showgrid=False, visible=False
)

fig.update_xaxes(title="Season", showgrid=False)

fig.update_traces(
    marker_symbol="circle",
    marker_size=20,
    textposition="middle center",
    textfont=dict(family="Arial", size=12, color="White"),
)


annotations = []


annotations.append(
    dict(
        text=f"Created by: SantaMonica @ MolochTH<br>Last update: {max_date}",
        xref="paper",
        yref="paper",
        x=1.16,
        y=-0.05,
        xanchor="right",
        yanchor="top",
        font=dict(family="Arial", size=12, color="rgb(150,150,150)"),
        showarrow=False,
    )
)

fig.update_layout(
    annotations=annotations,
    title_text=f"The Cookie Run Kingdom: Top 10 guilds in Dark Cacao Server <br>(Guild Ranking Over Time)",
    title_font_family="Arial",
    title_font_size=30,
    legend=dict(
        # x=0,
        # y=1,
        # traceorder="reversed",
        font=dict(family="Arial", size=20, color="black"),
        bgcolor=None,
        bordercolor=None,
        borderwidth=0,
    ),
    hovermode="closest",
)

fig.show()

In [18]:
report_path = r"report\top10_ranking_overtime.html"
fig.write_html(report_path)

## Ranking Over Time of Top 20

In [19]:
top10_recent = data[
    (data.Rank <= 10) & (data.Round == data.Round.max())
].GuildName.unique()

max_date = str(data[data.GuildName.isin(top10_recent)].Date.max()).split(" ")[0]

fig = px.line(
    data[(data.Rank <= 20)],
    x="Round",
    y="Rank",
    color="GuildNameExtra",
    color_discrete_sequence=px.colors.qualitative.G10,
    text="Rank",
    markers=True,
    line_shape="linear",
    labels={"GuildNameExtra": "Guild", "Round": "Season"},
    template="plotly_white",
    hover_name="GuildNameExtra",
    hover_data={
        "GuildNameExtra": False,
        "Round": True,
        "Rank": False,
        "Date": "|%d %B %Y",
        "Trophies": ":,.0f",
        "SeasonTotal": ":,.0f",
    },
    height=1100,
    width=1600,
)


fig.update_yaxes(
    title="Rank", ticklabelstep=1, range=[21, 0], showgrid=False, visible=False
)

fig.update_xaxes(title="Season", showgrid=False)

fig.update_traces(
    marker_symbol="circle",
    marker_size=20,
    textposition="middle center",
    textfont=dict(family="Arial", size=11, color="White"),
)


annotations = []


annotations.append(
    dict(
        text=f"Created by: SantaMonica @ MolochTH<br>Last update: {max_date}",
        xref="paper",
        yref="paper",
        x=1.2,
        y=-0.05,
        xanchor="right",
        yanchor="top",
        font=dict(
            family="Arial",
            size=10,
            color="rgb(150,150,150)",
        ),
        showarrow=False,
    )
)

fig.update_layout(
    annotations=annotations,
    title_text=f"The Cookie Run Kingdom: Top 20 guilds in Dark Cacao Server <br>(Guild Ranking Over Time)",
    title_font_family="Arial",
    title_font_size=30,
    legend=dict(
        # x=0,
        # y=1,
        # traceorder="reversed",
        font=dict(
            family="Arial",
            size=15,
            color="black",
        ),
        bgcolor=None,
        bordercolor=None,
        borderwidth=None,
    ),
    hovermode="closest",
)

fig.show()

In [20]:
report_path = r"report\top20_ranking_overtime.html"
fig.write_html(report_path)

---


In [35]:
(np.arange(2001, 2014),) * 4

(array([2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
        2012, 2013]),
 array([2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
        2012, 2013]),
 array([2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
        2012, 2013]),
 array([2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
        2012, 2013]))

In [21]:
plot_data = rep_table.T

plot_data.loc[["Trophies"], :].values


plot_data.columns.values

x_data = np.vstack(
    tup=(np.array(plot_data.index.get_level_values(level=1).values),) * 20
)

len(x_data)

20

In [22]:
plot_data.loc[["Rank"], :].values

array([[2, 1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 17, 18, 20,
        16, <NA>, <NA>, 19, <NA>],
       [2, 1, 3, 6, 4, 5, 7, 8, 9, 10, 11, 12, 13, 14, 15, 18, 17, 20,
        16, <NA>, <NA>, 19, <NA>],
       [2, 1, 3, 5, 4, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 18, 17, 20,
        16, <NA>, <NA>, 19, <NA>],
       [2, 1, 3, 4, 5, 6, 8, 7, 9, 10, 11, 12, 14, 13, 15, 16, 17, 18,
        19, 21, 20, <NA>, <NA>],
       [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, <NA>, <NA>, <NA>],
       [1, 2, 3, 4, 5, 6, 7, 9, 8, 10, 11, 12, 13, 14, 16, 15, 17, 18,
        19, 20, <NA>, <NA>, <NA>],
       [1, 2, 3, 6, 4, 7, 5, 8, 9, 10, 11, 12, 14, 13, 18, 19, 16, 17,
        15, 20, <NA>, <NA>, <NA>],
       [1, 2, 3, 6, 4, 7, 5, 8, 9, 10, 11, 12, 14, 13, 19, 18, 16, 17,
        15, 20, <NA>, <NA>, <NA>],
       [1, 2, 3, 5, 6, 8, 4, 7, 9, 10, 11, 12, 15, 13, 18, 19, 16, 17,
        14, 20, <NA>, <NA>, <NA>],
       [1, 2, 3, 5, 6, 8, 4, 7, 11, 10, 12, 13, 

# PyGWalker

In [22]:
import pygwalker as pyg

walker = pyg.walk(data)

Box(children=(HTML(value='<div id="ifr-pyg-0006197132ece703qFkf7WXrHeYIjnd4" style="height: auto">\n    <head>…

## Guild Boss Trophies Over Time

In [23]:
fig = px.line(
    data[data.GuildName.isin(top10_recent)],
    x="Round",
    y="Trophies",
    color="GuildName",
    color_discrete_sequence=px.colors.qualitative.G10_r,
    markers=True,
    hover_data={
        "GuildName": False,
        "Rank": ":,.0f",
        "Date": "|%B %d, %Y",
        "Trophies": ":,.0f",
    },
    hover_name="GuildName",
    title="Guild Boss Trophies Over Time",
    labels={"Rank": "Rank", "Round": "Season", "Trophies": "Trophies"},
    template="simple_white",
    height=800,
)


fig.update_yaxes(showgrid=True)


fig.show()

In [24]:
report_path = r"report\top10_trophies_overtime.html"
fig.write_html(report_path)

## Example

In [25]:
title = "Main Source for News"
labels = ["Television", "Newspaper", "Internet", "Radio"]
colors = ["rgb(67,67,67)", "rgb(115,115,115)", "rgb(49,130,189)", "rgb(189,189,189)"]

mode_size = [8, 8, 12, 8]
line_size = [2, 2, 4, 2]

x_data = np.vstack((np.arange(2001, 2014),) * 4)

y_data = np.array(
    [
        [74, 82, 80, 74, 73, 72, 74, 70, 70, 66, 66, 69],
        [45, 42, 50, 46, 36, 36, 34, 35, 32, 31, 31, 28],
        [13, 14, 20, 24, 20, 24, 24, 40, 35, 41, 43, 50],
        [18, 21, 18, 21, 16, 14, 13, 18, 17, 16, 19, 23],
    ]
)
print(list(zip(y_data, labels, colors)))

x_data

[(array([74, 82, 80, 74, 73, 72, 74, 70, 70, 66, 66, 69]), 'Television', 'rgb(67,67,67)'), (array([45, 42, 50, 46, 36, 36, 34, 35, 32, 31, 31, 28]), 'Newspaper', 'rgb(115,115,115)'), (array([13, 14, 20, 24, 20, 24, 24, 40, 35, 41, 43, 50]), 'Internet', 'rgb(49,130,189)'), (array([18, 21, 18, 21, 16, 14, 13, 18, 17, 16, 19, 23]), 'Radio', 'rgb(189,189,189)')]


array([[2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
        2012, 2013],
       [2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
        2012, 2013],
       [2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
        2012, 2013],
       [2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
        2012, 2013]])

# Example

In [26]:
fig = go.Figure()

for i in range(0, 4):
    fig.add_trace(
        go.Scatter(
            x=x_data[i],
            y=y_data[i],
            mode="lines",
            name=labels[i],
            line=dict(color=colors[i], width=line_size[i]),
            connectgaps=True,
        )
    )

    # endpoints
    fig.add_trace(
        go.Scatter(
            x=[x_data[i][0], x_data[i][-1]],
            y=[y_data[i][0], y_data[i][-1]],
            mode="markers",
            marker=dict(color=colors[i], size=mode_size[i]),
        )
    )

fig.update_layout(
    xaxis=dict(
        showline=True,
        showgrid=False,
        showticklabels=True,
        linecolor="rgb(204, 204, 204)",
        linewidth=2,
        ticks="outside",
        tickfont=dict(
            family="Arial",
            size=12,
            color="rgb(82, 82, 82)",
        ),
    ),
    yaxis=dict(
        showgrid=False,
        zeroline=False,
        showline=False,
        showticklabels=False,
    ),
    autosize=False,
    margin=dict(
        autoexpand=False,
        l=100,
        r=20,
        t=110,
    ),
    showlegend=False,
    plot_bgcolor="white",
)

annotations = []

# Adding labels
for y_trace, label, color in zip(y_data, labels, colors):
    # labeling the left_side of the plot
    annotations.append(
        dict(
            xref="paper",
            x=0.05,
            y=y_trace[0],
            xanchor="right",
            yanchor="middle",
            text=label + " {}%".format(y_trace[0]),
            font=dict(family="Arial", size=16),
            showarrow=False,
        )
    )
    # labeling the right_side of the plot
    annotations.append(
        dict(
            xref="paper",
            x=0.95,
            y=y_trace[11],
            xanchor="left",
            yanchor="middle",
            text="{}%".format(y_trace[11]),
            font=dict(family="Arial", size=16),
            showarrow=False,
        )
    )
# Title
annotations.append(
    dict(
        xref="paper",
        yref="paper",
        x=0.0,
        y=1.05,
        xanchor="left",
        yanchor="bottom",
        text="Main Source for News",
        font=dict(family="Arial", size=30, color="rgb(37,37,37)"),
        showarrow=False,
    )
)
# Source
annotations.append(
    dict(
        xref="paper",
        yref="paper",
        x=0.5,
        y=-0.1,
        xanchor="center",
        yanchor="top",
        text="Source: PewResearch Center & " + "Storytelling with data",
        font=dict(family="Arial", size=12, color="rgb(150,150,150)"),
        showarrow=False,
    )
)

fig.update_layout(annotations=annotations)

fig.show()

# waterfall

In [23]:
data

Date Season Round Rank  GuildName GuildNameExtra  Trophies  \
0   2024-02-27      1   1-1    1  Spearmint      Spearmint  10513190   
1   2024-02-27      1   1-1    2      Vivid          Vivid  10510940   
2   2024-02-27      1   1-1    3    Nobless        Nobless  10251975   
3   2024-02-27      1   1-1    4      LAODA          LAODA  10011795   
4   2024-02-27      1   1-1    5        미라클  미라클 (miracle)   9930645   
..         ...    ...   ...  ...        ...            ...       ...   
281 2024-05-28      4   4-3   16       MyTH           MyTH  10346185   
282 2024-05-28      4   4-3   17   Nobility       Nobility  10445040   
283 2024-05-28      4   4-3   18       S7AR           S7AR  10270005   
284 2024-05-28      4   4-3   19         감동  감동 (gam-dong)   9872795   
285 2024-05-28      4   4-3   20     DEKWAT         DEKWAT  10286850   

     SeasonTotal  Improvement  GrowthRate  
0       10513190            0    0.000000  
1       10510940            0    0.000000  
2       10251975            0    0.000000  
3       10011795            0    0.000000  
4        9930645            0    0.000000  
..           ...          ...         ...  
281     30139130       401815    4.040628  
282     30041855       570010    5.772236  
283     29984580       327380    3.292692  
284     29384460        79735    0.814199  
285     29698740       585060    6.030434  

[286 rows x 10 columns]

In [24]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Assuming data2 is the DataFrame with the added "GrowthRate" column

fig = go.Figure()


for guild, dat in data.groupby("GuildName"):
    growth_rates_percentage = dat["GrowthRate"]
    fig.add_trace(
        go.Waterfall(
            orientation="v",
            x=dat["Round"],
            y=growth_rates_percentage,
            name=guild,
            # text=f"{guild}",
            decreasing=dict(marker=dict(color="red")),
            increasing=dict(marker=dict(color="green")),
        )
    )

fig.update_layout(
    title="Waterfall Chart for Growth Rate over Time",
    xaxis_title="Round",
    yaxis_title="Growth Rate (%)",
    autosize=False,
    width=800,
    height=600,
    # yaxis=dict(type="log"),  # Set the y-axis type to logarithmic
)

fig.show()

In [25]:
top10_recent = data[
    (data.Rank <= 10) & (data.Round == data.Round.max())
].GuildName.unique()

data[data.GuildName.isin(top10_recent)]


def view_table(df):

    return df.style.format(
        precision=2,
        thousands=",",
        decimal=".",
    )


# view_table(data[data.GuildName.isin(top10_recent)])

In [26]:
data_top10 = data[data.GuildName.isin(top10_recent)]
fig = make_subplots(rows=5, cols=2, subplot_titles=data_top10.GuildNameExtra.unique())

for i, guild in enumerate(data_top10):
    dataset = data_top10
    growth_rates_percentage = dataset["GrowthRate"]
    fig.add_trace(
        go.Waterfall(
            orientation="v",
            x=dataset["Round"],
            y=growth_rates_percentage,
            name=guild,
            text=f"{guild}",  # ({growth_rates_percentage.astype(str)}%)",
            decreasing=dict(marker=dict(color="red")),
            increasing=dict(marker=dict(color="green")),
        ),
        col=(i // 5) + 1,  # Calculate the row number
        row=(i % 5) + 1,  # Calculate the column number
    )

fig.update_layout(
    title="Waterfall Chart for Top 10 Guilds (Formatted as Percentage)",
    xaxis_title="Round",
    yaxis_title="Growth Rate (%)",
    autosize=True,
    grid=dict(rows=5, columns=2, pattern="independent"),
)

fig.show()